### ISSUE TITLE
Move to Distributions?

### ISSUE THREAD

**Issue by devmotion** [theogf/KLDivergences.jl#12]
I suggest moving the implementations to Distributions, and I would approve a PR. This would fix the type piracy problems inherent in this package (it extends a function it does not own for types it does not own, it seems).

**Comment by theogf** [comment]
I suppose you speak about: https://github.com/theogf/KLDivergences.jl/blob/bcb3de7636c1505e18cfdfba0097a698a3cbf66e/src/KLDivergences.jl#L24 . I could delete it if that's a problem...

Wouldn't that make Distributions.jl even more heavy? The advantage of keeping KLDivergences.jl out is that it would be easier to make it more AD friendly than in Distributions.jl (adding Chain rules etc...)

**Comment by devmotion** [comment]
> Wouldn't that make Distributions.jl even more heavy? 

`kldivergence` is defined in StatsBase on which Distributions already depends. Distributions also already defines a fallback for `kldivergence` for univariate distributions. In general, to me it seems just as an additional part of the StatsBase API that is implemented for distributions, as e.g. `entropy`, `median` etc.

> The advantage of keeping KLDivergences.jl out is that it would be easier to make it more AD friendly than in Distributions.jl (adding Chain rules etc...)

Distributions uses ChainRulesCore and there is a lot of ongoing work to improve AD compatibility. In fact, many more recent changes are motivated by AD.

**Comment by theogf** [comment]
Ok I guess I have not looked into into Distributions.jl for a while...
I will make a PR to Distributions.jl then. What do you think about the extension of `kldivergence(p, q, n_samples)` to indicate the number of samples wanted?

**Comment by devmotion** [comment]
>  What do you think about the extension of `kldivergence(p, q, n_samples)` to indicate the number of samples wanted?

I think it is not a good idea since the three-argument version already has a different meaning (https://juliastats.org/StatsBase.jl/latest/scalarstats/#StatsBase.kldivergence) and even definition (https://github.com/JuliaStats/StatsBase.jl/blob/0a179531f14d0140356fcf1f1d55bd0240030cf2/src/scalarstats.jl#L627-L628). I could imagine that keyword argument(s) could be useful in some cases though (also in https://github.com/JuliaStats/Distributions.jl/blob/35125579a77b938f8d4a8bd2be23cbf1f2ddf225/src/functionals.jl#L32-L34 to be able to specify the tolerance of `expectation`).

**Comment by theogf** [comment]
Oh fair point! Good that I asked :D
