### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by azev77** [theogf/KLDivergences.jl#2]
Hi and thanks for this package. 

Is [this](https://github.com/theogf/KLDivergences.jl/blob/334150053120e9aa4c81283f7d9c4c42cf4ed785/src/univariate.jl#L2) a typo? 

Instead of: 
`return logbeta(q.α, q.β) - logbeta(q.α, q.β) + (p.α - q.α) * digamma(p.α) +`
Should it be:
`return logbeta(q.α, q.β) - logbeta(p.α, p.β) + (p.α - q.α) * digamma(p.α) +`

**Comment by theogf** [comment]
Oh you are absolutely right. I will correct it
